Pandas Demonstration
====================

In [1]:
# Import all three modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Data Cleaning
----------------
1. **Handling Missing Values**: Use `pd.isnull()` to identify missing values and `pd.fillna()` to fill them with a specified value or method (e.g., forward fill, backward fill).
2. **Removing Duplicates**: Use `pd.drop_duplicates()` to remove duplicate rows from the DataFrame.
3. **Data Type Conversion**: Use `pd.to_numeric()`, `pd.to_datetime()`, or `pd.astype()` to convert data types of columns as needed.

In [3]:
# Dictionary to create Series
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
}

In [4]:
d1 = pd.Series(data)
print(d1)

Name    [Alice, Bob, Charlie, David, Eve]
dtype: object

In [5]:
# Dictionary to create DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

In [6]:
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix

In [7]:
# generate a dictionary with 100 entries to demonstrate data cleaning
data = {
    'Name': ['Person ' + str(i) for i in range(1, 101)],
    'Age': [np.random.choice([25, 30, 35, 40, 45, None]) for _ in range(100)],
    'City': [np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', None]) for _ in range(100)]
}

In [8]:
df = pd.DataFrame(data)
print(df)

          Name   Age         City
0     Person 1  40.0      Chicago
1     Person 2  45.0          NaN
2     Person 3  30.0  Los Angeles
3     Person 4  40.0      Chicago
4     Person 5  30.0          NaN
..         ...   ...          ...
95   Person 96  45.0     New York
96   Person 97  35.0      Phoenix
97   Person 98  40.0  Los Angeles
98   Person 99  45.0      Phoenix
99  Person 100  40.0      Houston

[100 rows x 3 columns]

In [10]:
df.head(3)

       Name   Age         City
0  Person 1  40.0      Chicago
1  Person 2  45.0          NaN
2  Person 3  30.0  Los Angeles

In [11]:
df.tail(3)

          Name   Age         City
97   Person 98  40.0  Los Angeles
98   Person 99  45.0      Phoenix
99  Person 100  40.0      Houston

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    100 non-null    str
 1   Age     82 non-null     float64
 2   City    79 non-null     str
dtypes: float64(1), str(2)
memory usage: 2.5 KB

1. dropna() - Remove rows with missing values
2. fillna() - Fill missing values with a specified value or method
3. duplications - Remove duplicate rows

In [13]:
df1 = df.copy()
df1.dropna(inplace=True)
df1.info()

<class 'pandas.DataFrame'>
Index: 65 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    65 non-null     str
 1   Age     65 non-null     float64
 2   City    65 non-null     str
dtypes: float64(1), str(2)
memory usage: 2.0 KB

In [14]:
df2 = df.copy()
df2.fillna({'Age': df2['Age'].mean(), 'City': 'Unknown'}, inplace=True)
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    100 non-null    str
 1   Age     100 non-null    float64
 2   City    100 non-null    str
dtypes: float64(1), str(2)
memory usage: 2.5 KB

In [15]:
# Example data with wrong data types
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': ['25', '30', '35', '40', '45'],  # Age as strings
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

In [16]:
df = pd.DataFrame(data)
print(df)

      Name Age         City
0    Alice  25     New York
1      Bob  30  Los Angeles
2  Charlie  35      Chicago
3    David  40      Houston
4      Eve  45      Phoenix

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      str
 2   City    5 non-null      str
dtypes: str(3)
memory usage: 252.0 bytes

In [18]:
df1 = df.copy()
df1['Age'] = df1['Age'].astype(int)
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [21]:
# data with wrong date format
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Birthdate': ['01-01-1990', '02/02/1985', '03-03-1980', '04-04-1975', '05-05-1970']  # Wrong format
}
df = pd.DataFrame(data)
print(df)

      Name   Birthdate
0    Alice  01-01-1990
1      Bob  02/02/1985
2  Charlie  03-03-1980
3    David  04-04-1975
4      Eve  05-05-1970

In [22]:
# Fix the date format
df['Birthdate'] = pd.to_datetime(df['Birthdate'], format='%d-%m-%Y')
print(df)

ValueError: time data "02/02/1985" doesn't match format "%d-%m-%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [25]:
# Extract date from Bob user
bob_birthdate = df.loc[df['Name'] == 'Bob', 'Birthdate'].iloc[0]
print(f"Bob's Birthdate: {bob_birthdate}")
# Fix the date format of Bob's birthdate from '02/02/1985' to '02-02-1985'
bob_birthdate_extracted = pd.to_datetime(bob_birthdate, format='%d/%m/%Y')
print(f"Bob's Birthdate after fixing format: {bob_birthdate_extracted}")
# Now we can update the DataFrame with the fixed birthdate for Bob
fixed_birthdate = bob_birthdate_extracted.strftime('%d-%m-%Y')
df.loc[df['Name'] == 'Bob', 'Birthdate'] = fixed_birthdate
print(df)

Bob's Birthdate: 02/02/1985
Bob's Birthdate after fixing format: 1985-02-02 00:00:00
      Name   Birthdate
0    Alice  01-01-1990
1      Bob  02-02-1985
2  Charlie  03-03-1980
3    David  04-04-1975
4      Eve  05-05-1970